Fixes

diff --git a/.diploi/helm/app.yaml b/.diploi/helm/app.yaml
--- a/.diploi/helm/app.yaml
+++ b/.diploi/helm/app.yaml
@@ -85,13 +85,13 @@ spec:
               if [ -f yarn.lock ]; then yarn run build; \
               elif [ -f package-lock.json ]; then npm run build; \
               elif [ -f pnpm-lock.yaml ]; then pnpm run build; \
-              else echo "Lockfile not found. Skipping runtime build. This usually means the image was built without __VITE_RUNTIME_BUILD set to true in diploi.yaml. See the README for details."; \
+              else echo "Lockfile not found. Skipping runtime build. This usually means the image was built without __VITE_RUNTIME_BUILD set to true in diploi.yaml. See the README for details." && exit 0; \
               fi &&
-              find /build -mindepth 1 -exec rm -rf {} + &&
+              find /build -mindepth 1 -maxdepth 1 -exec rm -rf {} + &&
               DEST=$(pwd | awk '{sub("/app","/build");print}') &&
               mkdir -p $DEST &&
-              cp -rv ./dist $DEST ||: &&
               cp -r ./node_modules $DEST ||: &&
+              cp -rv ./dist $DEST ||: &&
               chown -R 1000:1000 /build
           workingDir: /app{{ .Values.folder }}
           volumeMounts:
